project:
  type: default

format:
  html:
    toc: true
    toc-location: right
    toc-title: "Table of Contents"
    toc-depth: 4
    theme: cosmo
    css: custom.css
    code-fold: true
    code-tools: true
    smooth-scroll: true
